---
name: Build CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Run tests
        run: |
          just test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Install jq
        run: |
          sudo apt-get install jq

      - name: Build binary
        run: |
          just tidy
          BASE_VERSION="$(jq -r .version .github/specs.json)"
          BUILD_VERSION_CI="${BASE_VERSION}-ci"
          just build "$BUILD_VERSION_CI"

      - name: Run binary
        run: |
          ./lazyfile --version
          ./lazyfile --help
